#include "claraKeyMap.h"

const QMap<Qt::Key, QString> ClaraKeyMap::keyMapSmallCase{
    {Qt::Key_A, "a"},
    {Qt::Key_B, "b"},
    {Qt::Key_C, "c"},
    {Qt::Key_D, "d"},
    {Qt::Key_E, "e"},
    {Qt::Key_F, "f"},
    {Qt::Key_G, "g"},
    {Qt::Key_H, "h"},
    {Qt::Key_I, "i"},
    {Qt::Key_J, "j"},
    {Qt::Key_K, "k"},
    {Qt::Key_L, "l"},
    {Qt::Key_M, "m"},
    {Qt::Key_N, "n"},
    {Qt::Key_O, "o"},
    {Qt::Key_P, "p"},
    {Qt::Key_Q, "q"},
    {Qt::Key_R, "r"},
    {Qt::Key_S, "s"},
    {Qt::Key_T, "t"},
    {Qt::Key_U, "u"},
    {Qt::Key_V, "v"},
    {Qt::Key_W, "w"},
    {Qt::Key_X, "x"},
    {Qt::Key_Y, "y"},
    {Qt::Key_Z, "z"}
};
